import { ComponentFixture, TestBed } from '@angular/core/testing';
import { signal, WritableSignal } from '@angular/core';
import { provideNoopAnimations } from '@angular/platform-browser/animations';
import { User, URN } from '@nx-platform-application/platform-types';
import {
  IAuthService,
  AUTH_API_URL,
} from '@nx-platform-application/platform-auth-access';
import { LoginComponent } from './login';

const mockUser: User = {
  id: URN.parse('urn:contacts:user:1'),
  alias: 'Test User',
  email: 'test@example.com',
};

describe('LoginComponent', () => {
  let fixture: ComponentFixture<LoginComponent>;
  let mockAuthService: Partial<IAuthService>;
  let isAuthenticatedSignal: WritableSignal<boolean>;
  let currentUserSignal: WritableSignal<User | null>;

  beforeEach(async () => {
    isAuthenticatedSignal = signal(false);
    currentUserSignal = signal(null);

    mockAuthService = {
      isAuthenticated: isAuthenticatedSignal.asReadonly(),
      currentUser: currentUserSignal.asReadonly(),
      logout: vi.fn(),
    };

    await TestBed.configureTestingModule({
      imports: [LoginComponent],
      providers: [
        { provide: IAuthService, useValue: mockAuthService },
        { provide: AUTH_API_URL, useValue: 'http://test-api' }, // Provider added
        provideNoopAnimations(),
      ],
    }).compileComponents();

    fixture = TestBed.createComponent(LoginComponent);
    fixture.detectChanges();
  });

  afterEach(() => {
    vi.clearAllMocks();
    TestBed.resetTestingModule();
  });

  it('should show login button when not authenticated', () => {
    isAuthenticatedSignal.set(false);
    fixture.detectChanges();

    // Note: Matches the URL generated by the mock AUTH_API_URL
    const loginButton = fixture.nativeElement.querySelector(
      'a[href="http://test-api/google"]',
    );
    const logoutButton = fixture.nativeElement.querySelector('button');

    expect(loginButton).toBeTruthy();
    expect(loginButton.textContent).toContain('Login with Google');
    expect(logoutButton).toBeFalsy();
  });

  it('should show welcome message and logout button when authenticated', () => {
    isAuthenticatedSignal.set(true);
    currentUserSignal.set(mockUser);
    fixture.detectChanges();

    const welcomeMessage = fixture.nativeElement.querySelector('h2');
    const logoutButton = fixture.nativeElement.querySelector('button');
    const loginButton = fixture.nativeElement.querySelector('a');

    expect(welcomeMessage.textContent).toContain('Welcome, Test User!');
    expect(logoutButton).toBeTruthy();
    expect(logoutButton.textContent).toContain('Logout');
    expect(loginButton).toBeFalsy();
  });

  it('should call authService.logout when logout button is clicked', () => {
    isAuthenticatedSignal.set(true);
    currentUserSignal.set(mockUser);
    fixture.detectChanges();

    const logoutButton = fixture.nativeElement.querySelector('button');
    logoutButton.click();

    expect(mockAuthService.logout).toHaveBeenCalledTimes(1);
  });
});
