import { Signal } from '@angular/core';
import { URN } from '@nx-platform-application/platform-types';
import { Contact, ContactGroup, IdentityLink, BlockedIdentity, PendingIdentity } from '@nx-platform-application/contacts-types';
import * as i0 from "@angular/core";
export declare class ContactsStateService {
    private storage;
    private gatekeeper;
    readonly contacts$: import("rxjs").Observable<Contact[]>;
    readonly groups$: import("rxjs").Observable<ContactGroup[]>;
    readonly blocked$: import("rxjs").Observable<BlockedIdentity[]>;
    readonly pending$: import("rxjs").Observable<PendingIdentity[]>;
    readonly contacts: Signal<Contact[]>;
    readonly favorites: Signal<Contact[]>;
    readonly groups: Signal<ContactGroup[]>;
    readonly blocked: Signal<BlockedIdentity[]>;
    readonly pending: Signal<PendingIdentity[]>;
    private readonly contactMap;
    resolveContact(urn: URN | string | null | undefined): Signal<Contact | undefined>;
    getContactSnapshot(urn: URN): Contact | undefined;
    resolveContactName(urn: URN | string | null | undefined): Signal<string>;
    isBlocked(urn: URN, scope: string): Promise<boolean>;
    isTrusted(urn: URN, scope?: string): Promise<boolean>;
    createContact(alias: string, networkId?: URN): Promise<URN>;
    getGroupParticipants(groupUrn: URN): Promise<Contact[]>;
    saveContact(contact: Contact): Promise<void>;
    deleteContact(id: URN): Promise<void>;
    saveGroup(group: ContactGroup): Promise<void>;
    deleteGroup(id: URN): Promise<void>;
    getGroupsByParent(parentId: URN): Promise<ContactGroup[]>;
    getGroupsForContact(contactId: URN): Promise<ContactGroup[]>;
    getLinkedIdentities(contactId: URN): Promise<URN[]>;
    blockIdentity(urn: URN, scopes?: string[]): Promise<void>;
    unblockIdentity(urn: URN): Promise<void>;
    deletePending(urn: URN): Promise<void>;
    addToPending(urn: URN, vouchedBy?: URN, note?: string): Promise<void>;
    getPendingIdentity(urn: URN): Promise<PendingIdentity | null>;
    getAllIdentityLinks(): Promise<IdentityLink[]>;
    clearDatabase(): Promise<void>;
    performContactsWipe(): Promise<void>;
    getContact(id: URN): Promise<Contact | undefined>;
    getGroup(id: URN): Promise<ContactGroup | undefined>;
    private formatUnknownUrn;
    static ɵfac: i0.ɵɵFactoryDeclaration<ContactsStateService, never>;
    static ɵprov: i0.ɵɵInjectableDeclaration<ContactsStateService>;
}
