import { Injectable, inject } from '@angular/core';
import { URN } from '@nx-platform-application/platform-types';
import { OutboundService } from '@nx-platform-application/messenger-domain-sending';
import {
  MessageTypingIndicator,
  ReadReceiptData,
  ContactShareData,
  ImageContent,
  TextContent,
  MessageTypeText,
  MessageTypeImage,
  MessageTypeReadReceipt,
  AssetRevealData,
  MessageTypeAssetReveal,
  MessageTypeContactShare,
  ContentPayload,
  RichContent,
} from '@nx-platform-application/messenger-domain-message-content';

import { ConversationService } from './conversation.service';
import { SendOptions } from '@nx-platform-application/messenger-domain-sending';

@Injectable({ providedIn: 'root' })
export class ConversationActionService {
  private outbound = inject(OutboundService);
  private conversationState = inject(ConversationService);

  private operationLock = Promise.resolve();

  async sendMessage(recipientUrn: URN, text: string): Promise<void> {
    // ✅ RICH HANDOFF: Pass object, not bytes.
    const payload: TextContent = { kind: 'text', text };
    const typeId = MessageTypeText;
    await this.sendGeneric(recipientUrn, typeId, payload);
  }

  async sendImage(recipientUrn: URN, content: ImageContent): Promise<string> {
    // ✅ RICH HANDOFF: Pass ImageContent object directly.
    const typeId = MessageTypeImage;
    return await this.sendGeneric(recipientUrn, typeId, content);
  }

  async sendContactShare(
    recipientUrn: URN,
    data: ContactShareData,
  ): Promise<void> {
    // ✅ RICH HANDOFF: Construct RichContent object.
    const payload: RichContent = {
      kind: 'rich',
      subType: 'contact-share',
      data: data,
    };
    const typeId = MessageTypeContactShare;
    await this.sendGeneric(recipientUrn, typeId, payload);
  }

  // --- SIGNALS (Still using Bytes for ephemeral/metadata types) ---

  async sendTypingIndicator(recipientUrn: URN): Promise<void> {
    const typeId = MessageTypingIndicator;
    const bytes = new Uint8Array([]);
    await this.runExclusive(() =>
      this.outbound.sendFromConversation(recipientUrn, typeId, bytes, {
        isEphemeral: true,
        shouldPersist: false,
      }),
    );
  }

  async sendReadReceiptSignal(
    recipientUrn: URN,
    messageIds: string[],
  ): Promise<void> {
    const data: ReadReceiptData = {
      messageIds,
      readAt: new Date().toISOString(),
    };
    // Signals are still serialized manually as they bypass standard content parsing
    const bytes = new TextEncoder().encode(JSON.stringify(data));
    const typeId = MessageTypeReadReceipt;

    await this.sendGeneric(recipientUrn, typeId, bytes, {
      shouldPersist: false,
    });
  }

  async sendAssetReveal(
    recipientUrn: URN,
    data: AssetRevealData,
  ): Promise<void> {
    const bytes = new TextEncoder().encode(JSON.stringify(data));
    const typeId = MessageTypeAssetReveal;
    await this.sendGeneric(recipientUrn, typeId, bytes, {
      shouldPersist: false,
    });
  }

  /**
   * Generic sender wrapper.
   */
  private async sendGeneric(
    recipientUrn: URN,
    typeId: URN,
    content: ContentPayload | Uint8Array, // Updated Signature
    options?: SendOptions,
  ): Promise<string> {
    return this.runExclusive(async () => {
      const result = await this.outbound.sendFromConversation(
        recipientUrn,
        typeId,
        content,
        options,
      );

      if (result) {
        const { message, outcome } = result;

        if (options?.shouldPersist ?? true) {
          // 1. Optimistic Update (Show 'pending' in Chat Window)
          // The message now contains a valid snippet generated by OutboundService
          this.conversationState.upsertMessages([message]);

          // 2. Async Confirmation (Update to 'sent'/'failed')
          outcome.then((finalStatus) => {
            if (finalStatus !== 'pending') {
              this.conversationState.updateMessageStatusInSignal(
                message.id,
                finalStatus,
              );
            }
          });
        }

        return message.id;
      }
      throw new Error('Send failed');
    });
  }

  private async runExclusive<T>(task: () => Promise<T>): Promise<T> {
    const previousLock = this.operationLock;
    let releaseLock: () => void;
    this.operationLock = new Promise((resolve) => {
      releaseLock = resolve;
    });
    try {
      await previousLock;
      return await task();
    } finally {
      releaseLock!();
    }
  }
}
